version: '2'
services:

  conjur:
    image: registry2.itci.conjur.net/conjur-appliance:4.9-stable
    container_name: conjur-master
    ports:
      - "443:443"
    volumes:
      - ./policies:/src/policies
    security_opt:
      - "seccomp:unconfined"
  
  s3-worker:
    build:
      context: .
      dockerfile: build/ansible/Dockerfile
    container_name: s3-worker
    volumes:
      - ./playbooks:/src/playbooks
      - ./certs:/src/certs
      - ./assets:/src/assets
      - /var/run/docker.sock:/var/run/docker.sock
