version: '2'
services:

  conjur:
    image: registry2.itci.conjur.net/conjur-appliance:4.9-stable
    container_name: conjur-master
    ports:
      - "443:443"
    volumes:
      - ./policies:/src/policies
    security_opt:
      - "seccomp:unconfined"

  conjur-cli:
    build:
      context: .
      dockerfile: build/conjur-cli/Dockerfile
    container_name: conjur-cli
    environment:
      CONJUR_APPLIANCE_URL: https://conjur-master
      CONJUR_ACCOUNT: demo
      CONJUR_AUTHN_LOGIN: admin
      CONJUR_AUTHN_API_KEY: Cyberark1
    volumes:
      - ./policies:/src/policies
      - ./certs:/src/certs
    links:
      - conjur
  
  ansible:
    build:
      context: .
      dockerfile: build/ansible/Dockerfile
    container_name: ansible
    volumes:
      - ./playbooks:/src/playbooks
      - ./certs:/src/certs
      - ./assets:/src/assets
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - conjur
