- hosts: all 
  gather_facts: false

  roles:
    - role: cyberark.conjur-host-identity
      conjur_appliance_url: 'https://conjur-master/api'
      conjur_account: 'demo'
      conjur_host_factory_token: '{{ lookup("env", "HFTOKEN") }}'
      conjur_host_name: 's3-downloader'
      conjur_ssl_certificate: '{{ lookup("file", "/src/certs/ca.crt") }}'
      conjur_validate_certs: true
    
    - role: ssilab.aws-cli
      aws_output_format: 'json'
      aws_region: '{{ lookup("env", "AWS_DEFAULT_REGION") }}'
      aws_access_key_id: '{{ lookup("env", "AWS_ACCESS_KEY_ID") }}'
      aws_secret_access_key: '{{ lookup("env", "AWS_SECRET_ACCESS_KEY") }}'

  tasks:
    - name: Download HIPAA Authorization Form from AWS S3 unencrypted
      shell: "aws s3 cp s3://conjur-sse-c-s3-demo/hipaa-authorization-unencrypted.pdf /src/assets/downloads/"
    - name: Run Summon Test - Pull AES256 Key from Conjur
      shell: "summon --yaml 'AES_KEY: !var aws-sse-c/aws-s3/aes256_key' printenv AES_KEY"
      register: aes256_key
    - name: Show AES256 Key Returned Value from Conjur
      debug:
        var: aes256_key
    - name: Download HIPAA Authorization Form from AWS S3 decrypted w/ AES256 Key (SSE-C)
      shell: "summon --yaml 'AES_KEY: !var aws-sse-c/aws-s3/aes256_key' bash -c \"aws s3 cp s3://conjur-sse-c-s3-demo/hipaa-authorization-AES256.pdf /src/assets/downloads/ --sse-c AES256 --sse-c-key $AES_KEY\""
